# Numpy  : Numeric Computing libray

In [1]:
import numpy as np

In [2]:
np.int32

numpy.int32

#  NUmpy Arrays

In [6]:
 a = np.array([1,2,3,4,5])

In [7]:
a[0]

1

In [8]:
a[1:3]

array([2, 3])

In [10]:
a[::-1]

array([5, 4, 3, 2, 1])

In [11]:
a[1],a[3] ,a[-1]


(2, 4, 5)

In [14]:
a[[1,-1,2]]

array([2, 5, 3])

In [15]:
a.dtype

dtype('int32')

In [19]:
b = np.a

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3489715020.py, line 1)