# Numpy  : Numeric Computing libray

In [2]:
import numpy as np


In [2]:
np.int32

numpy.int32

#  NUmpy Arrays

In [6]:
 a = np.array([1,2,3,4,5])

In [7]:
a[0]

1

In [8]:
a[1:3]

array([2, 3])

In [10]:
a[::-1]

array([5, 4, 3, 2, 1])

In [11]:
a[1],a[3] ,a[-1]


(2, 4, 5)

In [14]:
a[[1,-1,2]]

array([2, 5, 3])

In [15]:
a.dtype

dtype('int32')

# Broadcasting and Vectorized operations

In [3]:
a = np.arange(4) 

In [4]:
a

array([0, 1, 2, 3])

In [5]:
a + 10

array([10, 11, 12, 13])

In [6]:
a * 10

array([ 0, 10, 20, 30])

In [7]:
a 

array([0, 1, 2, 3])

In [8]:
a += 10

In [9]:
a

array([10, 11, 12, 13])

# Numpy Boolean Arrays

In [11]:
a[[True, False, False, True]]

array([10, 13])

In [12]:
a[a >= 11]

array([11, 12, 13])

In [13]:
a > 12

array([False, False, False,  True])